# Generated by Django 4.2.5 on 2023-09-24 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 18, 4, 13, 265991, tzinfo=datetime.timezone.utc)),
        ),
    ]
